name: Generate snake animation

on:
  schedule: # eseguito ogni 12 ore
    - cron: "*/12 * * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: genera snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: spingi snake.svg nel branch di output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          source_dir: dist  # Questo è il parametro che mancava
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
